apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullName" . }}
  labels:
    chart: {{ template "chartName" . }}
spec:
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ template "fullName" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.internalPort | int }}
        resources:
{{ toYaml .Values.resources | indent 10 }}